[versions]
# 2021.2.1, matching grammarkit version
ideaVersion = "212.5080.55"
kotlin = "1.6.10"

[libraries]
intellijCore = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "ideaVersion" }
intellijLang = { module = "com.jetbrains.intellij.platform:lang-impl", version.ref = "ideaVersion" }
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.6" }
spotless = { id = "com.diffplug.spotless", version = "5.11.1" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.14.2" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version = "1.3.1" }