[versions]
ideaVersion = "213.7172.25" # Dolphin (2021.3.1) Patch 1 (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
kotlin = "1.8.0"

[libraries]
intellijCoreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "ideaVersion" }
intellijProjectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "ideaVersion" }
intellijAnalysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "ideaVersion" }
intellijIndexing = { module = "com.jetbrains.intellij.platform:indexing", version.ref = "ideaVersion" }
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"

[bundles]
intelliJ = ["intellijCoreImpl", "intellijProjectModelImpl", "intellijAnalysisImpl", "intellijIndexing"]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.11" }
spotless = { id = "com.diffplug.spotless", version = "6.12.1" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.23.1" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
intellij = { id = "org.jetbrains.intellij", version = "1.12.0" }
