[versions]
# 2021.2.1, matching grammarkit version
ideaVersion = "222.4459.24"
kotlin = "1.7.22"

[libraries]
intellijCoreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "ideaVersion" }
intellijProjectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "ideaVersion" }
intellijAnalysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "ideaVersion" }
intellijIndexing = { module = "com.jetbrains.intellij.platform:indexing", version.ref = "ideaVersion" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"

[bundles]
intelliJ = ["intellijCoreImpl", "intellijProjectModelImpl", "intellijAnalysisImpl", "intellijIndexing"]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.2.0" }
spotless = { id = "com.diffplug.spotless", version = "6.12.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
intellij = { id = "org.jetbrains.intellij", version = "1.10.0" }
