[versions]
ideaVersion = "222.4459.24" # Flamingo | 2022.2.1 (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
kotlin = "1.8.21"

[libraries]
intellijCoreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "ideaVersion" }
intellijProjectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "ideaVersion" }
intellijAnalysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "ideaVersion" }
intellijIndexing = { module = "com.jetbrains.intellij.platform:indexing", version.ref = "ideaVersion" }
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.4"

[bundles]
intelliJ = ["intellijCoreImpl", "intellijProjectModelImpl", "intellijAnalysisImpl", "intellijIndexing"]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.12" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.25.2" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
intellij = { id = "org.jetbrains.intellij", version = "1.14.0" }
