name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Execute a build
      run: ./gradlew build :sample-plugin:buildPlugin --stacktrace

    - run: ./gradlew runPluginVerifier

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
