name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Execute a build
      run: ./gradlew build --stacktrace

    - name: Verify plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        ide-versions: |
          ideaIC:2020.1
          ideaIU:2020.1

    - name: Get log file path and print contents
      if: failure()
      run: |
        echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
